### ISSUE TITLE
(node:2432) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: 

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8-riscv-ci#8]
```
$ npm start

> v8-riscv-ci@1.0.0 start /home/v8-ci/v8-riscv-ci
> npx nodemon index.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
Testing riscv/v8 PR #507
Send pending for precheck to PR #507
Pre-check PR #507
(node:2432) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"Status","code":"custom","field":"target_url","message":"target_url must use http(s) scheme"}
    at /home/v8-ci/v8-riscv-ci/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lazyparser** [comment]
not a bug.
wrong config.
fixed.
